### ISSUE TITLE
Image alt attributes: Flickr image (Page 17)

### ISSUE THREAD

**Issue by gtvj** [nationalarchives/tna-components#28]
This is a site-wide change that can best be addressed by creating a component in tna-components. The new component should: 

- [ ] Use `figure` and `figcaption`
- [ ] Make the `alt` text on the img tag an empty string (See GDS guidance - link posted below)

**Comment by bethmorr** [comment]
https://www.gov.uk/guidance/content-design/image-copyright-standards-for-gov-uk

**Comment by AshTNA** [comment]
The Flickr image is being removed by the rebrand.
The newsletter icon is currently a background image in the tna-base rebrand TEST pages, and will most likely be the same for the tna theme.

 See @domingobishop or @sdwilkes for more information regarding rebrand changes

**Comment by netdesignr** [comment]
The Flikr image is being removed as part of the rebrand
