### ISSUE TITLE
Non-descriptive link text (Page 47)

### ISSUE THREAD

**Issue by gtvj** [nationalarchives/tna-components#40]
This is the 'back to top' link that appears on our WordPress sites. Could the assigned developer please: 

- [ ] Remove the existing script from target environments (https://github.com/nationalarchives/tna-base/blob/2f1a8ac1b4d2dc12d3e24a262f5ff33c2b495ef1/js/back-to-top.js), recompile JS and deploy 
- [ ] Add a new React component that achieves the same 
- [ ] Deploy this to all target environments (incl. Discovery)

**Comment by netdesignr** [comment]
Decided to remove the back to top button from TNA and TNA-BASE repositories. The fix is on both test environments and the feature branches were merged into `develop`

**Comment by netdesignr** [comment]
- [X ] Fix this in TNA
- [x] Fix this in TNA-BASE
